#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Teremoq contributors
# SPDX-License-Identifier: Apache-2.0
set -Eeuo pipefail

TEST_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd -- "${TEST_DIR}/.." && pwd -P)"
agent="${ROOT}/client/Lan-Interactive-Agent.mjs"
recovery="${ROOT}/client/Repair-LanUpdaterSlots.ps1"
launcher="${ROOT}/client/Start-LanInteractiveClient.ps1"
control="${ROOT}/interactive-channel-control.sh"
channel="${ROOT}/interactive_channel.py"
firewall="${ROOT}/windows/Firewall-Lan.ps1"

grep -Fq 'C:\\Program Files\\Git\\cmd\\git.exe' "${agent}"
grep -Fq 'C:\Program Files\Git\cmd\git.exe' "${launcher}"
grep -Fq 'node_modules\\npm\\bin\\npm-cli.js' "${agent}"
! grep -Fq 'runProcess("npm.cmd"' "${agent}"
! grep -Fq 'diagnose-build' "${agent}"
! grep -Fq '"build:lan"' "${agent}"
! grep -Fq '"diagnose-build"' "${channel}"
grep -Fq 'allowed = {"update-client", "prepare-client"}' "${channel}"
grep -Fq 'expected exactly one matching active LAN channel client' "${recovery}"
grep -Fq "@('checkout-updater-a', 'checkout-updater-b')" "${recovery}"
grep -Fq 'Remove-TeremoqBoundedRegularTree -Path $slot -ExpectedParent $clientRoot' "${recovery}"
grep -Fq 'Get-TeremoqGitCheckoutContext -CheckoutRoot $activeCheckout' "${recovery}"
if grep -Eqi 'Remove-Item.+(config|evidence|state)|wsl|firewall|pairing|management-token' "${recovery}"; then
    printf 'interactive-channel-policy-test: updater recovery broadened into protected channel or client state\n' >&2
    exit 1
fi
grep -Fq 'UPDATE_REPOSITORY_URL = "https://github.com/Teremoq/teremoq"' "${channel}"
grep -Fq 'UPDATE_REPOSITORY_REF = "refs/heads/codex/lan-e2e-integration"' "${channel}"
grep -Fq '"update-client": "Actualizar el cliente desde GitHub"' "${agent}"
grep -Fq -- '--credential-mode' "${launcher}"
grep -Fq 'taskkill.exe' "${agent}"
grep -Fq 'taskkill_status=' "${agent}"
grep -Fq 'termination-residue' "${agent}"
grep -Fq 'residual_process_pid=' "${agent}"
grep -Fq '[Parameter(Mandatory = $true)][string]$ExpectedCommit' "${launcher}"
! grep -Fq 'ExpectedLauncherSha256' "${launcher}"
grep -Fq 'Get-TeremoqProtectedExecutableSha256' "${launcher}"
grep -Fq 'StandardError.ReadToEndAsync()' "${launcher}"
grep -Fq 'Get-TeremoqSafeAgentError' "${launcher}"
grep -Fq 'sendTerminalEventWithFallback' "${agent}"
grep -Fq 'truncateUtf8Tail' "${agent}"
grep -Fq '$sessionRestart -gt 120' "${launcher}"
grep -Fq 'if (-not $ResumeSessionStdin)' "${launcher}"
grep -Fq '$ResumeSessionStdin -and $sessionRestart -eq 0' "${launcher}"
grep -Fq 'Start-Sleep -Seconds 2' "${launcher}"
grep -Fq 'CHANNEL_RETRY_MAX_ATTEMPTS = 120' "${agent}"
grep -Fq 'validateEventAck' "${agent}"
grep -Fq 'event replay differs from the recorded event' "${channel}"
grep -Fq 'pairing recovery is blocked while a task is pending' "${channel}"
grep -Fq 'self.document["session_sha256"] = None' "${channel}"
grep -Fq 'recover-pairing' "${control}"
grep -Fq '/v1/recover-pairing' "${channel}"
grep -Fq -- '--next-client-commit' "${control}"
grep -Fq 'self.document["client_commit"] = request["next_client_commit"]' "${channel}"
grep -Fq 'coordination listener reloaded; state, credentials and network evidence retained' "${channel}"
grep -Fq -- '--confirm-reload' "${control}"
grep -Fq 'except EventMessageError:' "${channel}"
grep -Fq -- "'--taskkill-sha256'" "${launcher}"
grep -Fq '[IO.FileShare]::Read' "${launcher}"
grep -Fq 'Get-TeremoqStreamGitBlobId' "${launcher}"
grep -Fq "'ls-tree','-r','--full-tree'" "${launcher}"
grep -Fq 'cancel_requested' "${channel}"
grep -Fq 'daemon-start' "${control}"
grep -Fq 'daemon-stop' "${control}"
grep -Fq 'channel-process.json' "${channel}"
grep -Fq 'revoke-authorization' "${channel}"
grep -Fq 'remove_new_state_root' "${channel}"
grep -Fq 'verify-startup-clean' "${channel}"
! grep -Fq 'channel.pid' "${control}"
! grep -Fq 'nohup' "${control}"
! grep -Fq 'rm -f' "${control}"
! grep -Fq 'tail -n' "${control}"
! grep -Fq '${state_root}/' "${control}"
grep -Fq -- '--confirm-start' "${control}"
grep -Fq -- '--confirm-authorize' "${channel}"
! grep -Eq 'start\|enqueue\|status\|stop\|cleanup|^[[:space:]]*cleanup\)' "${control}"
grep -Fq "CoordinationTlsPort -notin @(0, 18443)" "${firewall}"
grep -Fq 'RemoteAddress = $ClientIPv4' "${firewall}"

printf 'lan-interactive-channel-policy-test: PASS\n'
